/* opxx(a,b) OP##a is the enumerate no of operator b */
opxx(RET, " r ")
opxx(NEG, "-") 
opxx(PLUS, " + " ) 
opxx(MINUS, " - ") 
opxx(MULT, " * ") 
opxx(DIV, " / ") 
opxx(MOD, " % ") 
opxx(ASGN, " = ") 
opxx(EQL, " == ")
opxx(NEQ, " != " ) 
opxx(LSS, " < ") 
opxx(GEQ, " >= ") 
opxx(GTR, " > ") 
opxx(LEQ, " <= ")
opxx(ANDAND, " && ")
opxx(OROR, " || ")
opxx(NOT, "!")
opxx(AND, " & ")
opxx(OR, " | ")
opxx(XOR, " ^ ")
opxx(LSH, " << ")
opxx(RSH, " >> ")
opxx(BITNOT,"~")
opxx(INDEX, " [] ")
opxx(CALL, " () ")
opxx(DEREF,"*")
opxx(ADDRESS,"&")
opxx(REF,"@")
opxx(CAST,"#")
opxx(READ,"Cin>>")
opxx(WRITE,"Cout<<")
opxx(SIZEOF,"sizeof")
